// Client/src/chat/Emote.tsx
import React from "react";

type Props = {
    id: string;
}
const Emote: React.FunctionComponent<Props> = ({id}: Props) => {
    return <img
        className="emote"
        alt={id}
        src={`https://static-cdn.jtvnw.net/emoticons/v1/${id}/4.0`}
        srcSet={`https://static-cdn.jtvnw.net/emoticons/v1/${id}/2.0 2x, https://static-cdn.jtvnw.net/emoticons/v1/${id}/3.0 4x`}/>
}

export default Emote;

// Client-Svelte/src/chat/Emote.svelte
<script lang="ts">
  export let id: string;
  export let code: string;

  export let scale: number;
  let emoteStyle: string;
  $: emoteStyle = `height: ${1.1 * scale}vw;` 

</script>

<style>
  .emote {
    display: inline-block;
    width: auto;
    display: inline-block;
    vertical-align: middle;
  }
</style>
 
<img class="emote" alt={id} style={emoteStyle}
  src={`https://static-cdn.jtvnw.net/emoticons/v1/${id}/4.0`}
  srcSet={`https://static-cdn.jtvnw.net/emoticons/v1/${id}/2.0 2x, https://static-cdn.jtvnw.net/emoticons/v1/${id}/3.0 4x`}
/>
