// Client-Svelte/src/chat/Badge.svelte
<script lang="ts">
  export let name: string;
  export let version: string;

  const ids = {
    "1979-revolution_1-1": "7833bb6e-d20d-48ff-a58d-67fe827a4f84",
    "60-seconds_1-1": "1e7252f9-7e80-4d3d-ae42-319f030cca99",
    "60-seconds_2-1": "64513f7d-21dd-4a05-a699-d73761945cf9",
    "60 -seconds_3-1": "f4306617-0f96-476f-994e-5304f81bcc6e",
    "H1Z1_1-1": "fc71386c-86cd-11e7-a55d-43f591dc0c71",
    "admin-1": "9ef7e029-4cdf-4d4d-a0d5-e2b3fb2583fe",
    "anomaly-2_1-1": "d1d1ad54-40a6-492b-882e-dcbdce5fa81e",
    "anomaly-warzone-earth_1-1": "858be873-fb1f-47e5-ad34-657f40d3d156",
    "anonymous-cheerer-1": "ca3db7f7-18f5-487e-a329-cd0b538ee979",
    "axiom-verge_1-1": "f209b747-45ee-42f6-8baf-ea7542633d10",
    "battlechefbrigade_1-1": "24e32e67-33cd-4227-ad96-f0a7fc836107",
    "battlechefbrigade_2-1": "ef1e96e8-a0f9-40b6-87af-2977d3c004bb",
    "battlechefbrigade_3-1": "107ebb20-4fcd-449a-9931-cd3f81b84c70",
    "battlerite_1-1": "484ebda9-f7fa-4c67-b12b-c80582f3cc61",
    "bits-1": "73b5c3fb-24f9-4a82-a852-2f475b59411c",
    "bits-100": "09d93036-e7ce-431c-9a9e-7044297133f2",
    "bits-1000": "0d85a29e-79ad-4c63-a285-3acd2c66f2ba",
    "bits-5000": "57cd97fc-3e9e-4c6d-9d41-60147137234e",
    "bits-10000": "68af213b-a771-4124-b6e3-9bb6d98aa732",
    "bits-25000": "64ca5920-c663-4bd8-bfb1-751b4caea2dd",
    "bits-50000": "62310ba7-9916-4235-9eba-40110d67f85d",
    "bits-75000": "ce491fa4-b24f-4f3b-b6ff-44b080202792",
    "bits-100000": "96f0540f-aa63-49e1-a8b3-259ece3bd098",
    "bits-200000": "4a0b90c4-e4ef-407f-84fe-36b14aebdbb6",
    "bits-300000": "ac13372d-2e94-41d1-ae11-ecd677f69bb6",
    "bits-400000": "a8f393af-76e6-4aa2-9dd0-7dcc1c34f036",
    "bits-500000": "f6932b57-6a6e-4062-a770-dfbd9f4302e5",
    "bits-600000": "4d908059-f91c-4aef-9acb-634434f4c32e",
    "bits-700000": "a1d2a824-f216-4b9f-9642-3de8ed370957",
    "bits-800000": "5ec2ee3e-5633-4c2a-8e77-77473fe409e6",
    "bits-900000": "088c58c6-7c38-45ba-8f73-63ef24189b84",
    "bits-1000000": "494d1c8e-c3b2-4d88-8528-baff57c9bd3f",
    "bits-1250000": "ce217209-4615-4bf8-81e3-57d06b8b9dc7",
    "bits-1500000": "c4eba5b4-17a7-40a1-a668-bc1972c1e24d",
    "bits-1750000": "183f1fd8-aaf4-450c-a413-e53f839f0f82",
    "bits-2000000": "7ea89c53-1a3b-45f9-9223-d97ae19089f2",
    "bits-2500000": "cf061daf-d571-4811-bcc2-c55c8792bc8f",
    "bits-3000000": "5671797f-5e9f-478c-a2b5-eb086c8928cf",
    "bits-3500000": "c3d218f5-1e45-419d-9c11-033a1ae54d3a",
    "bits-4000000": "79fe642a-87f3-40b1-892e-a341747b6e08",
    "bits-4500000": "736d4156-ac67-4256-a224-3e6e915436db",
    "bits-5000000": "3f085f85-8d15-4a03-a829-17fca7bf1bc2",
    "bits-charity-1": "a539dc18-ae19-49b0-98c4-8391a594332b",
    "bits-leader-1": "8bedf8c3-7a6d-4df2-b62f-791b96a5dd31",
    "bits-leader-2": "f04baac7-9141-4456-a0e7-6301bcc34138",
    "bits-leader-3": "f1d2aab6-b647-47af-965b-84909cf303aa",
    "brawlhalla_1-1": "bf6d6579-ab02-4f0a-9f64-a51c37040858",
    "broadcaster-1": "5527c58c-fb7d-422d-b71b-f309dcb85cc1",
    "broken-age_1-1": "56885ed2-9a09-4c8e-8131-3eb9ec15af94",
    "bubsy-the-woolies_1-1": "c8129382-1f4e-4d15-a8d2-48bdddba9b81",
    "clip-champ-1": "f38976e0-ffc9-11e7-86d6-7f98b26a9d79",
    "cuphead_1-1": "4384659a-a2e3-11e7-a564-87f6b1288bab",
    "darkest-dungeon_1-1": "52a98ddd-cc79-46a8-9fe3-30f8c719bc2d",
    "deceit_1-1": "b14fef48-4ff9-4063-abf6-579489234fe9",
    "devil-may-cry-hd_1-1": "633877d4-a91c-4c36-b75b-803f82b1352f",
    "devil-may-cry-hd_2-1": "408548fe-aa74-4d53-b5e9-960103d9b865",
    "devil-may-cry-hd_3-1": "df84c5bf-8d66-48e2-b9fb-c014cc9b3945",
    "devil-may-cry-hd_4-1": "af836b94-8ffd-4c0a-b7d8-a92fad5e3015",
    "devilian_1-1": "3cb92b57-1eef-451c-ac23-4d748128b2c5",
    "duelyst_1-1": "7d9c12f4-a2ac-4e88-8026-d1a330468282",
    "duelyst_2-1": "1938acd3-2d18-471d-b1af-44f2047c033c",
    "duelyst_3-1": "344c07fc-1632-47c6-9785-e62562a6b760",
    "duelyst_4-1": "39e717a8-00bc-49cc-b6d4-3ea91ee1be25",
    "duelyst_5-1": "290419b6-484a-47da-ad14-a99d6581f758",
    "duelyst_6-1": "c5e54a4b-0bf1-463a-874a-38524579aed0",
    "duelyst_7-1": "cf508179-3183-4987-97e0-56ca44babb9f",
    "enter-the-gungeon_1-1": "53c9af0b-84f6-4f9d-8c80-4bc51321a37d",
    "eso_1-1": "18647a68-a35f-48d7-bf97-ae5deb6b277d",
    "extension-1": "ea8b0f8c-aa27-11e8-ba0c-1370ffff3854",
    "firewatch_1-1": "b6bf4889-4902-49e2-9658-c0132e71c9c4",
    "founder-0": "511b78a9-ab37-472f-9569-457753bbe7d3",
    "frozen-cortext_1-1": "2015f087-01b5-4a01-a2bb-ecb4d6be5240",
    "frozen-synapse_1-1": "d4bd464d-55ea-4238-a11d-744f034e2375",
    "getting-over-it_1-1": "8d4e178c-81ec-4c71-af68-745b40733984",
    "getting-over-it_2-1": "bb620b42-e0e1-4373-928e-d4a732f99ccb",
    "glhf-pledge-1": "3158e758-3cb4-43c5-94b3-7639810451c5",
    "global_mod-1": "9384c43e-4ce7-4e94-b2a1-b93656896eba",
    "heavy-bullets_1-1": "fc83b76b-f8b2-4519-9f61-6faf84eef4cd",
    "hello_neighbor_1-1": "030cab2c-5d14-11e7-8d91-43a5a4306286",
    "hype-train-1": "fae4086c-3190-44d4-83c8-8ef0cbe1a515",
    "hype-train-2": "9c8d038a-3a29-45ea-96d4-5031fb1a7a81",
    "innerspace_1-1": "97532ccd-6a07-42b5-aecf-3458b6b3ebea",
    "innerspace_2-1": "fc7d6018-657a-40e4-9246-0acdc85886d1",
    "jackbox-party-pack_1-1": "0f964fc1-f439-485f-a3c0-905294ee70e8",
    "kingdom-new-lands_1-1": "e3c2a67e-ef80-4fe3-ae41-b933cd11788a",
    "moderator-1": "3267646d-33f0-4b17-b3df-f923a41db1d0",
    "okhlos_1-1": "dc088bd6-8965-4907-a1a2-c0ba83874a7d",
    "overwatch-league-insider_1-1": "51e9e0aa-12e3-48ce-b961-421af0787dad",
    "overwatch-league-insider_2018B-1": "34ec1979-d9bb-4706-ad15-464de814a79d",
    "overwatch-league-insider_2019A-1": "ca980da1-3639-48a6-95a3-a03b002eb0e5",
    "overwatch-league-insider_2019A-2": "ab7fa7a7-c2d9-403f-9f33-215b29b43ce4",
    "overwatch-league-insider_2019B-1": "c5860811-d714-4413-9433-d6b1c9fc803c",
    "overwatch-league-insider_2019B-2": "75f05d4b-3042-415c-8b0b-e87620a24daf",
    "overwatch-league-insider_2019B-3": "765a0dcf-2a94-43ff-9b9c-ef6c209b90cd",
    "overwatch-league-insider_2019B-4": "a8ae0ccd-783d-460d-93ee-57c485c558a6",
    "overwatch-league-insider_2019B-5": "be87fd6d-1560-4e33-9ba4-2401b58d901f",
    "partner-1": "d12a2e27-16f6-41d0-ab77-b780518f00a3",
    "power-rangers-0": "9edf3e7f-62e4-40f5-86ab-7a646b10f1f0",
    "power-rangers-1": "1eeae8fe-5bc6-44ed-9c88-fb84d5e0df52",
    "power-rangers-2": "21bbcd6d-1751-4d28-a0c3-0b72453dd823",
    "power-rangers-3": "5c58cb40-9028-4d16-af67-5bc0c18b745e",
    "power-rangers-4": "8843d2de-049f-47d5-9794-b6517903db61",
    "power-rangers-5": "06c85e34-477e-4939-9537-fd9978976042",
    "power-rangers-6": "d6dca630-1ca4-48de-94e7-55ed0a24d8d1",
    "premium-1": "a1dd5073-19c3-4911-8cb4-c464a7bc1510",
    "psychonauts_1-1": "a9811799-dce3-475f-8feb-3745ad12b7ea",
    "raiden-v-directors-cut_1-1": "441b50ae-a2e3-11e7-8a3e-6bff0c840878",
    "rift_1-1": "f939686b-2892-46a4-9f0d-5f582578173e",
    "samusoffer_beta-0": "aa960159-a7b8-417e-83c1-035e4bc2deb5",
    "staff-1": "d97c37bd-a6f5-4c38-8f57-4e4bef88af34",
    "starbound_1-1": "e838e742-0025-4646-9772-18a87ba99358",
    "strafe_1-1": "0051508d-2d42-4e4b-a328-c86b04510ca4",
    "sub-gift-leader-1": "21656088-7da2-4467-acd2-55220e1f45ad",
    "sub-gift-leader-2": "0d9fe96b-97b7-4215-b5f3-5328ebad271c",
    "sub-gift-leader-3": "4c6e4497-eed9-4dd3-ac64-e0599d0a63e5",
    "sub-gifter-1": "f1d8486f-eb2e-4553-b44f-4d614617afc1",
    "sub-gifter-5": "3e638e02-b765-4070-81bd-a73d1ae34965",
    "sub-gifter-10": "bffca343-9d7d-49b4-a1ca-90af2c6a1639",
    "sub-gifter-25": "17e09e26-2528-4a04-9c7f-8518348324d1",
    "sub-gifter-50": "47308ed4-c979-4f3f-ad20-35a8ab76d85d",
    "sub-gifter-100": "5056c366-7299-4b3c-a15a-a18573650bfb",
    "sub-gifter-250": "df25dded-df81-408e-a2d3-40d48f0d529f",
    "sub-gifter-500": "f440decb-7468-4bf9-8666-98ba74f6eab5",
    "sub-gifter-1000": "b8c76744-c7e9-44be-90d0-08840a8f6e39",
    "subscriber-0": "5d9f2208-5dd8-11e7-8513-2ff4adfae661",
    "subscriber-1": "5d9f2208-5dd8-11e7-8513-2ff4adfae661",
    "superhot_1-1": "c5a06922-83b5-40cb-885f-bcffd3cd6c68",
    "the-surge_1-1": "c9f69d89-31c8-41aa-843b-fee956dfbe23",
    "the-surge_2-1": "2c4d7e95-e138-4dde-a783-7956a8ecc408",
    "the-surge_3-1": "0a8fc2d4-3125-4ccb-88db-e970dfbee189",
    "this-war-of-mine_1-1": "6a20f814-cb2c-414e-89cc-f8dd483e1785",
    "titan-souls_1-1": "092a7ce2-709c-434f-8df4-a6b075ef867d",
    "treasure-adventure-world_1-1": "59810027-2988-4b0d-b88d-fc414c751305",
    "turbo-1": "bd444ec6-8f34-4bf9-91f4-af1e3428d80f",
    "twitchbot-1": "df9095f6-a8a0-4cc2-bb33-d908c0adffb8",
    "twitchcon2017-1": "0964bed0-5c31-11e7-a90b-0739918f1d9b",
    "twitchcon2018-1": "e68164e4-087d-4f62-81da-d3557efae3cb",
    "twitchconAmsterdam2020-1": "ed917c9a-1a45-4340-9c64-ca8be4348c51",
    "twitchconEU2019-1": "590eee9e-f04d-474c-90e7-b304d9e74b32",
    "twitchconNA2019-1": "569c829d-c216-4f56-a191-3db257ed657c",
    "twitchconNA2020-1": "ed917c9a-1a45-4340-9c64-ca8be4348c51",
    "tyranny_1-1": "0c79afdf-28ce-4b0b-9e25-4f221c30bfde",
    "vga-champ-2017-1": "03dca92e-dc69-11e7-ac5b-9f942d292dc7",
    "vip-1": "b817aba4-fad8-49e2-b88a-7cc744dfa6ec",
    "warcraft-alliance": "c4816339-bad4-4645-ae69-d1ab2076a6b0",
    "warcraft-horde": "de8b26b6-fd28-4e6c-bc89-3d597343800d"
  };

  let index: string;
  $: index = `${name}-${version}`;

  let id: string | undefined;
  $: id = index in ids ? ids[index as keyof typeof ids] : undefined;

  export let scale: number;
  let badgeStyle: string;
  $: badgeStyle =
    `height: ${1.1 * scale}vw;` +
    `width: ${1.1 * scale}vw;` +
    `background-image: url(https://static-cdn.jtvnw.net/badges/v1/${id}/3);`
</script>

<style>
  .badge {
    display: inline-block;
    background-position: 0 center;
    background-repeat: no-repeat;
    background-size: contain;
    vertical-align: bottom;
    overflow: hidden;
  }
  
</style>

{#if id !== undefined}
    <span class="badge" style={badgeStyle}/>
{/if}

// Client/src/chat/Badge.tsx
import React from "react";

const ids = {
    "1979-revolution_1-1": "7833bb6e-d20d-48ff-a58d-67fe827a4f84",
    "60-seconds_1-1": "1e7252f9-7e80-4d3d-ae42-319f030cca99",
    "60-seconds_2-1": "64513f7d-21dd-4a05-a699-d73761945cf9",
    "60 -seconds_3-1": "f4306617-0f96-476f-994e-5304f81bcc6e",
    "H1Z1_1-1": "fc71386c-86cd-11e7-a55d-43f591dc0c71",
    "admin-1": "9ef7e029-4cdf-4d4d-a0d5-e2b3fb2583fe",
    "anomaly-2_1-1": "d1d1ad54-40a6-492b-882e-dcbdce5fa81e",
    "anomaly-warzone-earth_1-1": "858be873-fb1f-47e5-ad34-657f40d3d156",
    "anonymous-cheerer-1": "ca3db7f7-18f5-487e-a329-cd0b538ee979",
    "axiom-verge_1-1": "f209b747-45ee-42f6-8baf-ea7542633d10",
    "battlechefbrigade_1-1": "24e32e67-33cd-4227-ad96-f0a7fc836107",
    "battlechefbrigade_2-1": "ef1e96e8-a0f9-40b6-87af-2977d3c004bb",
    "battlechefbrigade_3-1": "107ebb20-4fcd-449a-9931-cd3f81b84c70",
    "battlerite_1-1": "484ebda9-f7fa-4c67-b12b-c80582f3cc61",
    "bits-1": "73b5c3fb-24f9-4a82-a852-2f475b59411c",
    "bits-100": "09d93036-e7ce-431c-9a9e-7044297133f2",
    "bits-1000": "0d85a29e-79ad-4c63-a285-3acd2c66f2ba",
    "bits-5000": "57cd97fc-3e9e-4c6d-9d41-60147137234e",
    "bits-10000": "68af213b-a771-4124-b6e3-9bb6d98aa732",
    "bits-25000": "64ca5920-c663-4bd8-bfb1-751b4caea2dd",
    "bits-50000": "62310ba7-9916-4235-9eba-40110d67f85d",
    "bits-75000": "ce491fa4-b24f-4f3b-b6ff-44b080202792",
    "bits-100000": "96f0540f-aa63-49e1-a8b3-259ece3bd098",
    "bits-200000": "4a0b90c4-e4ef-407f-84fe-36b14aebdbb6",
    "bits-300000": "ac13372d-2e94-41d1-ae11-ecd677f69bb6",
    "bits-400000": "a8f393af-76e6-4aa2-9dd0-7dcc1c34f036",
    "bits-500000": "f6932b57-6a6e-4062-a770-dfbd9f4302e5",
    "bits-600000": "4d908059-f91c-4aef-9acb-634434f4c32e",
    "bits-700000": "a1d2a824-f216-4b9f-9642-3de8ed370957",
    "bits-800000": "5ec2ee3e-5633-4c2a-8e77-77473fe409e6",
    "bits-900000": "088c58c6-7c38-45ba-8f73-63ef24189b84",
    "bits-1000000": "494d1c8e-c3b2-4d88-8528-baff57c9bd3f",
    "bits-1250000": "ce217209-4615-4bf8-81e3-57d06b8b9dc7",
    "bits-1500000": "c4eba5b4-17a7-40a1-a668-bc1972c1e24d",
    "bits-1750000": "183f1fd8-aaf4-450c-a413-e53f839f0f82",
    "bits-2000000": "7ea89c53-1a3b-45f9-9223-d97ae19089f2",
    "bits-2500000": "cf061daf-d571-4811-bcc2-c55c8792bc8f",
    "bits-3000000": "5671797f-5e9f-478c-a2b5-eb086c8928cf",
    "bits-3500000": "c3d218f5-1e45-419d-9c11-033a1ae54d3a",
    "bits-4000000": "79fe642a-87f3-40b1-892e-a341747b6e08",
    "bits-4500000": "736d4156-ac67-4256-a224-3e6e915436db",
    "bits-5000000": "3f085f85-8d15-4a03-a829-17fca7bf1bc2",
    "bits-charity-1": "a539dc18-ae19-49b0-98c4-8391a594332b",
    "bits-leader-1": "8bedf8c3-7a6d-4df2-b62f-791b96a5dd31",
    "bits-leader-2": "f04baac7-9141-4456-a0e7-6301bcc34138",
    "bits-leader-3": "f1d2aab6-b647-47af-965b-84909cf303aa",
    "brawlhalla_1-1": "bf6d6579-ab02-4f0a-9f64-a51c37040858",
    "broadcaster-1": "5527c58c-fb7d-422d-b71b-f309dcb85cc1",
    "broken-age_1-1": "56885ed2-9a09-4c8e-8131-3eb9ec15af94",
    "bubsy-the-woolies_1-1": "c8129382-1f4e-4d15-a8d2-48bdddba9b81",
    "clip-champ-1": "f38976e0-ffc9-11e7-86d6-7f98b26a9d79",
    "cuphead_1-1": "4384659a-a2e3-11e7-a564-87f6b1288bab",
    "darkest-dungeon_1-1": "52a98ddd-cc79-46a8-9fe3-30f8c719bc2d",
    "deceit_1-1": "b14fef48-4ff9-4063-abf6-579489234fe9",
    "devil-may-cry-hd_1-1": "633877d4-a91c-4c36-b75b-803f82b1352f",
    "devil-may-cry-hd_2-1": "408548fe-aa74-4d53-b5e9-960103d9b865",
    "devil-may-cry-hd_3-1": "df84c5bf-8d66-48e2-b9fb-c014cc9b3945",
    "devil-may-cry-hd_4-1": "af836b94-8ffd-4c0a-b7d8-a92fad5e3015",
    "devilian_1-1": "3cb92b57-1eef-451c-ac23-4d748128b2c5",
    "duelyst_1-1": "7d9c12f4-a2ac-4e88-8026-d1a330468282",
    "duelyst_2-1": "1938acd3-2d18-471d-b1af-44f2047c033c",
    "duelyst_3-1": "344c07fc-1632-47c6-9785-e62562a6b760",
    "duelyst_4-1": "39e717a8-00bc-49cc-b6d4-3ea91ee1be25",
    "duelyst_5-1": "290419b6-484a-47da-ad14-a99d6581f758",
    "duelyst_6-1": "c5e54a4b-0bf1-463a-874a-38524579aed0",
    "duelyst_7-1": "cf508179-3183-4987-97e0-56ca44babb9f",
    "enter-the-gungeon_1-1": "53c9af0b-84f6-4f9d-8c80-4bc51321a37d",
    "eso_1-1": "18647a68-a35f-48d7-bf97-ae5deb6b277d",
    "extension-1": "ea8b0f8c-aa27-11e8-ba0c-1370ffff3854",
    "firewatch_1-1": "b6bf4889-4902-49e2-9658-c0132e71c9c4",
    "founder-0": "511b78a9-ab37-472f-9569-457753bbe7d3",
    "frozen-cortext_1-1": "2015f087-01b5-4a01-a2bb-ecb4d6be5240",
    "frozen-synapse_1-1": "d4bd464d-55ea-4238-a11d-744f034e2375",
    "getting-over-it_1-1": "8d4e178c-81ec-4c71-af68-745b40733984",
    "getting-over-it_2-1": "bb620b42-e0e1-4373-928e-d4a732f99ccb",
    "glhf-pledge-1": "3158e758-3cb4-43c5-94b3-7639810451c5",
    "global_mod-1": "9384c43e-4ce7-4e94-b2a1-b93656896eba",
    "heavy-bullets_1-1": "fc83b76b-f8b2-4519-9f61-6faf84eef4cd",
    "hello_neighbor_1-1": "030cab2c-5d14-11e7-8d91-43a5a4306286",
    "hype-train-1": "fae4086c-3190-44d4-83c8-8ef0cbe1a515",
    "hype-train-2": "9c8d038a-3a29-45ea-96d4-5031fb1a7a81",
    "innerspace_1-1": "97532ccd-6a07-42b5-aecf-3458b6b3ebea",
    "innerspace_2-1": "fc7d6018-657a-40e4-9246-0acdc85886d1",
    "jackbox-party-pack_1-1": "0f964fc1-f439-485f-a3c0-905294ee70e8",
    "kingdom-new-lands_1-1": "e3c2a67e-ef80-4fe3-ae41-b933cd11788a",
    "moderator-1": "3267646d-33f0-4b17-b3df-f923a41db1d0",
    "okhlos_1-1": "dc088bd6-8965-4907-a1a2-c0ba83874a7d",
    "overwatch-league-insider_1-1": "51e9e0aa-12e3-48ce-b961-421af0787dad",
    "overwatch-league-insider_2018B-1": "34ec1979-d9bb-4706-ad15-464de814a79d",
    "overwatch-league-insider_2019A-1": "ca980da1-3639-48a6-95a3-a03b002eb0e5",
    "overwatch-league-insider_2019A-2": "ab7fa7a7-c2d9-403f-9f33-215b29b43ce4",
    "overwatch-league-insider_2019B-1": "c5860811-d714-4413-9433-d6b1c9fc803c",
    "overwatch-league-insider_2019B-2": "75f05d4b-3042-415c-8b0b-e87620a24daf",
    "overwatch-league-insider_2019B-3": "765a0dcf-2a94-43ff-9b9c-ef6c209b90cd",
    "overwatch-league-insider_2019B-4": "a8ae0ccd-783d-460d-93ee-57c485c558a6",
    "overwatch-league-insider_2019B-5": "be87fd6d-1560-4e33-9ba4-2401b58d901f",
    "partner-1": "d12a2e27-16f6-41d0-ab77-b780518f00a3",
    "power-rangers-0": "9edf3e7f-62e4-40f5-86ab-7a646b10f1f0",
    "power-rangers-1": "1eeae8fe-5bc6-44ed-9c88-fb84d5e0df52",
    "power-rangers-2": "21bbcd6d-1751-4d28-a0c3-0b72453dd823",
    "power-rangers-3": "5c58cb40-9028-4d16-af67-5bc0c18b745e",
    "power-rangers-4": "8843d2de-049f-47d5-9794-b6517903db61",
    "power-rangers-5": "06c85e34-477e-4939-9537-fd9978976042",
    "power-rangers-6": "d6dca630-1ca4-48de-94e7-55ed0a24d8d1",
    "premium-1": "a1dd5073-19c3-4911-8cb4-c464a7bc1510",
    "psychonauts_1-1": "a9811799-dce3-475f-8feb-3745ad12b7ea",
    "raiden-v-directors-cut_1-1": "441b50ae-a2e3-11e7-8a3e-6bff0c840878",
    "rift_1-1": "f939686b-2892-46a4-9f0d-5f582578173e",
    "samusoffer_beta-0": "aa960159-a7b8-417e-83c1-035e4bc2deb5",
    "staff-1": "d97c37bd-a6f5-4c38-8f57-4e4bef88af34",
    "starbound_1-1": "e838e742-0025-4646-9772-18a87ba99358",
    "strafe_1-1": "0051508d-2d42-4e4b-a328-c86b04510ca4",
    "sub-gift-leader-1": "21656088-7da2-4467-acd2-55220e1f45ad",
    "sub-gift-leader-2": "0d9fe96b-97b7-4215-b5f3-5328ebad271c",
    "sub-gift-leader-3": "4c6e4497-eed9-4dd3-ac64-e0599d0a63e5",
    "sub-gifter-1": "f1d8486f-eb2e-4553-b44f-4d614617afc1",
    "sub-gifter-5": "3e638e02-b765-4070-81bd-a73d1ae34965",
    "sub-gifter-10": "bffca343-9d7d-49b4-a1ca-90af2c6a1639",
    "sub-gifter-25": "17e09e26-2528-4a04-9c7f-8518348324d1",
    "sub-gifter-50": "47308ed4-c979-4f3f-ad20-35a8ab76d85d",
    "sub-gifter-100": "5056c366-7299-4b3c-a15a-a18573650bfb",
    "sub-gifter-250": "df25dded-df81-408e-a2d3-40d48f0d529f",
    "sub-gifter-500": "f440decb-7468-4bf9-8666-98ba74f6eab5",
    "sub-gifter-1000": "b8c76744-c7e9-44be-90d0-08840a8f6e39",
    "subscriber-0": "5d9f2208-5dd8-11e7-8513-2ff4adfae661",
    "subscriber-1": "5d9f2208-5dd8-11e7-8513-2ff4adfae661",
    "superhot_1-1": "c5a06922-83b5-40cb-885f-bcffd3cd6c68",
    "the-surge_1-1": "c9f69d89-31c8-41aa-843b-fee956dfbe23",
    "the-surge_2-1": "2c4d7e95-e138-4dde-a783-7956a8ecc408",
    "the-surge_3-1": "0a8fc2d4-3125-4ccb-88db-e970dfbee189",
    "this-war-of-mine_1-1": "6a20f814-cb2c-414e-89cc-f8dd483e1785",
    "titan-souls_1-1": "092a7ce2-709c-434f-8df4-a6b075ef867d",
    "treasure-adventure-world_1-1": "59810027-2988-4b0d-b88d-fc414c751305",
    "turbo-1": "bd444ec6-8f34-4bf9-91f4-af1e3428d80f",
    "twitchbot-1": "df9095f6-a8a0-4cc2-bb33-d908c0adffb8",
    "twitchcon2017-1": "0964bed0-5c31-11e7-a90b-0739918f1d9b",
    "twitchcon2018-1": "e68164e4-087d-4f62-81da-d3557efae3cb",
    "twitchconAmsterdam2020-1": "ed917c9a-1a45-4340-9c64-ca8be4348c51",
    "twitchconEU2019-1": "590eee9e-f04d-474c-90e7-b304d9e74b32",
    "twitchconNA2019-1": "569c829d-c216-4f56-a191-3db257ed657c",
    "twitchconNA2020-1": "ed917c9a-1a45-4340-9c64-ca8be4348c51",
    "tyranny_1-1": "0c79afdf-28ce-4b0b-9e25-4f221c30bfde",
    "vga-champ-2017-1": "03dca92e-dc69-11e7-ac5b-9f942d292dc7",
    "vip-1": "b817aba4-fad8-49e2-b88a-7cc744dfa6ec",
    "warcraft-alliance": "c4816339-bad4-4645-ae69-d1ab2076a6b0",
    "warcraft-horde": "de8b26b6-fd28-4e6c-bc89-3d597343800d"
}
type Props = {
    name: string;
    version: string;
}
const Badge: React.FunctionComponent<Props> = ({name, version}: Props) => {
    const index = (name + "-" + version) as keyof typeof ids;
    const id = ids[index];
    const url = `url(https://static-cdn.jtvnw.net/badges/v1/${id}/3)`
    return <span className="badge" style={{
        backgroundImage: url
    }}/>
}
// display: "inline-block",
//
//     backgroundRepeat: "no-repeat",
//     backgroundSize: "contain",
//     backgroundPosition: "center",
//     height: "100%",
//     width: "20px"


export default Badge;
